### PR TITLE
Add calendar info to home page

### PR DESCRIPTION
**Pull request by robsimmons**
This does two things, both of which may be silly and over-complicated, independently or taken together.

1) Makes a function that generates 42 calendar dates, and information about them, starting on a Sunday, such that the first day of the specified month (or current month) is among the first 7 dates, and 

2) Displays that table with some CSS grid nonsense that I've been learning about in CSS group.

## Visuals

If the page is wide enough it does fixed size calendar cells

image

If the page is narrower than 800 pixels it takes the full width and divides it evenly

image

## Testing

The function defaults to the current month and day, but we can play with different months

Let's move forward a month
```
            "calendar_dates": calendar_info(month=date(2023,11,13), today=date(2023, 11, 13)),
```
image

Weird edge case that will never show up in practice(???) where the current date is outside the current month
```
            "calendar_dates": calendar_info(month=date(2023,11,2), today=date(2023, 10, 30)),
```
image

### CODE REVIEW

**Comment by robsimmons** [comment]
I've created [a follow up ticket](https://github.com/gregsadetsky/nycnoise/issues/64) for the purpose of claiming that this PR closes #43

**Comment by gregsadetsky** [comment]
great work! very happy to approve as is -- I did however want to point out a few things that would be nice to have, if you're up for it of course!

the biggest thing that I see as an issue right now is the handling of timezones. as `date.today()` will run on the server in UTC, by ~8pm in New York, the date will be wrong (i.e. in the "future"). thankfully, this is *nyc* noise :-) so we know what timezone to handle/deal with.

feel free to either declare a django settings (EVENTS_DISPLAY_TIMEZONE or something? I would definitely definitely not touch the TIME_ZONE setting) or just hardcode us/newyork or whatever in your calendar date math. we can always extract it later.

the two other points are truly extras:
- it would be great to have a few tests -- specifically testing midnight @ utc would be a great one!
- it would also be nice to isolate the calendar html + css into its own sub-django template and then call `{% include %}`; I think we might want to move all of the css into its own file for now (so that it doesn't live at the top of index.html) as well

let me know if you have questions -- and thanks again for your work!!

**Comment by robsimmons** [comment]
All really good feedback! I may want to pair with you on the tests — might be a good pairing session to invite the django crew too?

**Comment by gregsadetsky** [comment]
> All really good feedback! I may want to pair with you on the tests — might be a good pairing session to invite the django crew too?

really great idea! can I let you lead the charge on arranging/announce this? and I'll definitely join and we can break ground on tests, which will be great!

do you want to fix the utc/timezone issue in this PR and I'll approve it then, or do you want to create a separate for the utc, and we can close this one as complete?

**Comment by gregsadetsky** [comment]
I also see there's a micro conflict to solve since we merged the latest PRs i.e. #63

**Comment by robsimmons** [comment]
I'll deal with that monday, no problem!

**Comment by robsimmons** [comment]
Didn't do it monday, but better late than never (perhaps). Used %include-ed fragments to separate out calendar styles and the calendar itself, and added pytz to get the nyctz

**Review by gregsadetsky — APPROVED** [review]
this looks really great, thank you!! merging

🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢

**Comment by gregsadetsky** [comment]
@all-contributors please add @robsimmons for code

**Pull request merged**
