### PR TITLE
Add user-facing event submission form

### PR DESCRIPTION
**Pull request by pfeyz**
This PR adds a submission form that allows users to submit events. They are required to include at least the following
- the time
- title OR artist info
- venue OR "venue name" (which is actually the venue override field)

submission-form

form validation is performed, and if successful, it redirects to the homepage and flashes a thanks message

thanks

all user-submitted events will be stored in the db with `is_approved=False` and `user_submitted=True`. 

all events with `is_approved=False` are filtered out from the calendar list of events.

then in the admin interface we can filter to just the `is_approved=False` entries to see the user-submitted events that still need to be checked and approved,

filtered

for now approving an event just means flipping that boolean field in the admin interface. maybe we could add some kind of moderation flow if it feels necessary next.

### CODE REVIEW

**Comment by pfeyz** [comment]
@nycnoise looking at it now I feel like it might be an intimidating form because it's not obvious that they only really need to fill out 3 of those fields. I can picture somebody looking at that form and getting scared away immediately, vs something like this:

simple

**Comment by gregsadetsky** [comment]
really great work, thanks so much!

if you still have time / energy, it would be great if the default Event manager (i.e. `[objects](https://docs.djangoproject.com/en/5.0/topics/db/managers/#manager-names)`) could be set to return approved events by default

[I use the same approach for static pages](https://github.com/gregsadetsky/nycnoise/blob/dev/core/models.py#L214) i.e. the regular `objects` returns a filtered view (only public pages) and there's a non-default `all_pages` that exists for any query which needs to show all of the objects

that way, it's safer -- you don't have to chase down all calls to StaticPage.objects and make sure that they filter out the non-public pages.

I'd love if the Event filtering was done in the same way - to reduce any chance of a user-submitted event from appearing anywhere.

small note: if you go this route, you'd have to change the queryset of the model admin class, otherwise the admin will also use the (new) `objects` and not show all objects. [you can see this done here for staticpage](https://github.com/gregsadetsky/nycnoise/blob/dev/core/admin.py#L184).

---

after the above is done, I'd also add two tests: 1) that a user submitted event does not show up on the homepage by default, and 2) that once a user submitted event is approved, it does show up on the homepage.

that's it! :-)

---

I agree with your point re: the form being intimidating - I think we could do a further iteration after merging this PR and think about either hiding optional fields, marking them as clearly being optional, etc. all possible & good improvements.

thanks again!

**Comment by gregsadetsky** [comment]
oh, and as noted by @nycnoise in https://github.com/gregsadetsky/nycnoise/issues/228 , we should also add a "closed" boolean field (defaulting to false) on all venues, so that "zzz___" venues right now can all be marked as closed (in the admin, in bulk) and then not show them in the submission form

**Comment by pfeyz** [comment]
thanks for the review and yes those are great ideas, will do!

**Comment by pfeyz** [comment]
@gregsadetsky I moved the unapproved event filtering into the Event manager and handled the change in the admin, added the tests you suggested and added a Venue.closed field that is hidden from the even submission form

**Comment by pfeyz** [comment]
awesome! I just submitted one through the form @nycnoise !

**Comment by nycnoise** [comment]
OMGGGGGG I'M JUST NOW SEEING THESE

**Comment by gregsadetsky** [comment]
@nycnoise obviously, if/when you feel that https://nyc-noise.com/submit-event is ready, you could link it in https://nyc-noise.com/submit/ -- obviously :-) lmk if anything is missing, etc.!

**Comment by nycnoise** [comment]
i JUST made an [issue](https://github.com/gregsadetsky/nycnoise/issues/239) w/ my MANY, MANY THOUGHTS –– apologies if i should have put that here?? anyway only need the "quick priority" to change before sharing, VERY EXCITED YAYYY

**Comment by gregsadetsky** [comment]
ah all good, a new issue is a good place for this! cheers

**Pull request merged**
