### PR TITLE
Evan event ics download link

### LINKED ISSUE #34: for each event, show a "add to iOS calendar" link to download an .ics file
similar to #33 , but for iOS devices

the site should let you download an .ics file for each event, which on iOS will show/open the built-in calendar app

we could use `https://icalendar.readthedocs.io/en/latest/usage.html#more-documentation` for this to create the .ics data and prompt a download when the link is clicked (i.e. send the write mime/http info so that browsers see it as a download)

### PR DESCRIPTION
**Pull request by evanconway**
resolves #34
Add a link to download an ics file (iCalendar) for each event. We can replace or move the link itself later. The real feature here is the url that generates an ics file for each event.

### CODE REVIEW

**Comment by evanconway** [comment]
After another look over, I think this is ready to go.

**Review by gregsadetsky — APPROVED** [review]
this is great, thank you! merging now (and will handle the conflicts created by the other recently PRs I just merged)

**Comment by gregsadetsky** [comment]
@all-contributors please add @evanconway for code

**Comment by gregsadetsky** [comment]
the other remaining thing I see with this is that the ics description should strip the html (also see [this discussion](https://stackoverflow.com/questions/854036/html-in-ical-attachment) on this topic)

just opened #75 for this

**Pull request merged**
