### PR TITLE
Gcal event link

### LINKED ISSUE #33: for each event, show a google calendar "add to gcal" link
for each event shown on the homepage, add a "add to gcal" link

the link should use the sorta-documented format of calendar.google.com links available [here](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/main/services/google.md)

### LINKED ISSUE #75: strip html from event description when including it in the ics file/download
#71 made it possible to download an ics file for events

however, per [this](https://stackoverflow.com/questions/854036/html-in-ical-attachment), it'd be preferable to strip the html from the description

this issue is to do exactly that :-)

I'd recommend stripping the html from the description tag using a standard django utility such as [this one](https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.html.strip_tags)

### PR DESCRIPTION
**Pull request by evanconway**
Create google calendar links for events.
resolves #33 
resolves #75

### CODE REVIEW

**Comment by evanconway** [comment]
Not ready to merge yet. Just opening the PR since it's close.

**Comment by evanconway** [comment]
https://github.com/gregsadetsky/nycnoise/issues/33#issuecomment-1765269278
Linking to Greg's comments to stay more organized.

**Comment by evanconway** [comment]
Need to double check if gcal links need an end time. And if so what is best default value. An hour?

**Comment by gregsadetsky** [comment]
yay on this PR!! feel free to convert it to "draft" until the moment you have a review. (just in case someone starts code reviewing it before it's ready..?) but no worries too, we're a small team :-)

great q re: end time!
- if the google cal link works without an end time, that would be best
- otherwise, yeah go for an hour. it's a perfectly reasonable default!

thank you!!

**Comment by evanconway** [comment]
@gregsadetsky Regarding your comment about custom tags, I got confused and wasn't able to add this on my own. Kept getting a "are you sure you registered this tag?" error despite using the `@register.simple_tag` decorator. However adding the link as a function in the model seems to streamline the code nicely. Happy to do it as a custom tag instead if that's preferable.

**Comment by gregsadetsky** [comment]
hey this is great! one thing is that it'd be preferable to use a more standard way of converting "regular text" into html arguments

i.e. these lines:
- https://github.com/gregsadetsky/nycnoise/pull/70/files#diff-880083c8a05dc4662af880cde1cf569e18f4476182e8680d2cee4cf1281a3d6eR19
- https://github.com/gregsadetsky/nycnoise/pull/70/files#diff-880083c8a05dc4662af880cde1cf569e18f4476182e8680d2cee4cf1281a3d6eR21
- https://github.com/gregsadetsky/nycnoise/pull/70/files#diff-880083c8a05dc4662af880cde1cf569e18f4476182e8680d2cee4cf1281a3d6eR22

... do a find replace for `" "` (space) and convert them to `"+"`

however, there are many other characters that would need to be url encoded (not just space -- the "+" character would need to be url encoded :-) and slashes... and most other chars). you can use the standard Django `urlencode` function for this:

```python
from django.utils.http import urlencode
urlencode({'somekey': 'some string that: / has weird characters'})
```

and it will do the right thing :-)

another point - just as noted in #75 , you'd want to strip any html from the description string here as well - before url encoding it!

let me know if I can help with this!

**Comment by evanconway** [comment]
@gregsadetsky I'm not sure I used `urlencode` exactly as you're supposed to, but it's certainly cleaner than before. This also fixes the html stripping issue now.

**Comment by gregsadetsky** [comment]
hey @evanconway thanks for all of your work!

let me know if these requests are getting annoying - I'm happy to make some of these changes. but, if you're still interested, here's the list of things I think would be good to see:

- I think that it's great that `.ics_string` and `.gcal_link` are methods on all `Event` objects, but having those those methods all be in the models.py file seems a bit not scalable i.e. if we keep adding methods (like, the actual method code) in models.py, those files will grow substantially.
  - hence, I'd recommend creating a file like utils_events.py, having the `gcal_link` and `ics_string` methods in there, but still have, in models.py, in the `Event` class, something like:

```python
from utils_events import gcal_link_for_event

class Event(...):
  ...
  def gcal_link(self):
    gcal_link_for_event(self)
```

(you had something close to this when you had the util.py file)

- I would not use a custom/our own strip tags method. it would be a better practice to use an existing one, and especially one that Django [provides us](https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.html.strip_tags) i.e. `strip_tags` -- could you please remove your own implementation and use this one instead?

thanks! let me know if you have any questions

**Comment by evanconway** [comment]
No worries! I want to be held to a high standard so I appreciate all nit-picks, no matter how small. I'll have that fixed by Monday.

**Comment by gregsadetsky** [comment]
hey, before you kill me from all the comments :-) could we get on a call? I think it will be easier to hash out

what I'm seeing now is that - if you look in the [diff](https://github.com/gregsadetsky/nycnoise/pull/70/files) -- a lot of things that were added to dev are now being removed in the merge. definitely not your fault - just a typical messy merge situation (I also didn't go through PRs so it's sort of actually 90%+ my fault!)

let me know if you have time - or let's just pair up in person at the hub if that works?

**Comment by evanconway** [comment]
Just messaged you in zulip. I "think" I properly fixed my botched merge but still happy to talk it out. I decided against doing something like this:
```python
from utils_events import gcal_link_for_event

class Event(...):
  ...
  def gcal_link(self):
    gcal_link_for_event(self)
```
Because I couldn't avoid circular imports. But the logic for both ics and gcal is out of the model now. Tags are stripped using Djangos method.

**Pull request merged**
